services:
  nextjs:
    container_name: nextjs-app
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .next:/app/.next
      - .npm:/app/.npm
    restart: unless-stopped
